-- AdProof — schema verification (READ-ONLY, safe to run anytime, changes nothing).
--
-- Run this in the Supabase project your APP points at — i.e. the <ref> in the
-- browser Network tab request to <ref>.supabase.co — NOT necessarily the one
-- you last pasted SETUP_ALL.sql into. It reports, against exactly what the
-- current app code expects, anything missing. A fully-migrated project returns
-- ONLY the single 'OK ...' summary row and nothing else.
--
-- Generated from supabase/SETUP_ALL.sql: 10 tables, 161 columns.

with expected_tables(t) as (values
    ('ad_breakdowns'),
    ('ad_outcomes'),
    ('audiences'),
    ('calibrations'),
    ('campaign_variants'),
    ('campaigns'),
    ('companies'),
    ('company_members'),
    ('creative_scores'),
    ('platform_connections')
),
expected_cols(t, c) as (values
    ('ad_breakdowns','ad_name'),
    ('ad_breakdowns','adset_name'),
    ('ad_breakdowns','age'),
    ('ad_breakdowns','campaign_name'),
    ('ad_breakdowns','clicks'),
    ('ad_breakdowns','company_id'),
    ('ad_breakdowns','conversions'),
    ('ad_breakdowns','created_at'),
    ('ad_breakdowns','gender'),
    ('ad_breakdowns','id'),
    ('ad_breakdowns','impressions'),
    ('ad_breakdowns','platform'),
    ('ad_breakdowns','provider'),
    ('ad_breakdowns','revenue'),
    ('ad_breakdowns','spend'),
    ('ad_breakdowns','user_id'),
    ('ad_breakdowns','window_end'),
    ('ad_breakdowns','window_start'),
    ('ad_outcomes','ad_copy'),
    ('ad_outcomes','ad_name'),
    ('ad_outcomes','adset_name'),
    ('ad_outcomes','audience'),
    ('ad_outcomes','campaign_name'),
    ('ad_outcomes','clicks'),
    ('ad_outcomes','company_id'),
    ('ad_outcomes','conversion_type'),
    ('ad_outcomes','conversions'),
    ('ad_outcomes','created_at'),
    ('ad_outcomes','creative_url'),
    ('ad_outcomes','currency'),
    ('ad_outcomes','date_end'),
    ('ad_outcomes','date_start'),
    ('ad_outcomes','format'),
    ('ad_outcomes','frequency'),
    ('ad_outcomes','geo'),
    ('ad_outcomes','id'),
    ('ad_outcomes','impressions'),
    ('ad_outcomes','objective'),
    ('ad_outcomes','platform'),
    ('ad_outcomes','product_price'),
    ('ad_outcomes','reach'),
    ('ad_outcomes','real_cpm'),
    ('ad_outcomes','real_ctr'),
    ('ad_outcomes','real_cvr'),
    ('ad_outcomes','real_roas'),
    ('ad_outcomes','revenue'),
    ('ad_outcomes','source_file'),
    ('ad_outcomes','spend'),
    ('ad_outcomes','test_group'),
    ('ad_outcomes','user_id'),
    ('audiences','company_id'),
    ('audiences','created_at'),
    ('audiences','description'),
    ('audiences','id'),
    ('audiences','name'),
    ('audiences','segment'),
    ('audiences','used_in_count'),
    ('audiences','user_id'),
    ('calibrations','backtest'),
    ('calibrations','company_id'),
    ('calibrations','created_at'),
    ('calibrations','id'),
    ('calibrations','n_ads'),
    ('calibrations','params'),
    ('calibrations','scope'),
    ('calibrations','user_id'),
    ('calibrations','window_from'),
    ('calibrations','window_to'),
    ('campaign_variants','campaign_id'),
    ('campaign_variants','created_at'),
    ('campaign_variants','ctr_pct'),
    ('campaign_variants','headline'),
    ('campaign_variants','id'),
    ('campaign_variants','label'),
    ('campaign_variants','original_request'),
    ('campaign_variants','result'),
    ('campaign_variants','thumbnail_url'),
    ('campaign_variants','user_id'),
    ('campaign_variants','verdict_class'),
    ('campaigns','audience_label'),
    ('campaigns','budget'),
    ('campaigns','company_id'),
    ('campaigns','created_at'),
    ('campaigns','ctr_pct'),
    ('campaigns','days'),
    ('campaigns','format_name'),
    ('campaigns','id'),
    ('campaigns','market_context'),
    ('campaigns','name'),
    ('campaigns','platform_name'),
    ('campaigns','rerun_of_id'),
    ('campaigns','thumbnail_url'),
    ('campaigns','updated_at'),
    ('campaigns','user_id'),
    ('campaigns','verdict_class'),
    ('companies','archived'),
    ('companies','avg_order_value'),
    ('companies','brand_color'),
    ('companies','brand_tone'),
    ('companies','business_model'),
    ('companies','conversion_goal'),
    ('companies','created_at'),
    ('companies','currency'),
    ('companies','id'),
    ('companies','industry'),
    ('companies','location'),
    ('companies','name'),
    ('companies','price_position'),
    ('companies','product_category'),
    ('companies','product_price'),
    ('companies','raw_description'),
    ('companies','sales_cycle'),
    ('companies','source'),
    ('companies','target_customer_summary'),
    ('companies','updated_at'),
    ('companies','user_id'),
    ('companies','usps'),
    ('companies','value_proposition'),
    ('companies','website'),
    ('company_members','accepted_at'),
    ('company_members','company_id'),
    ('company_members','created_at'),
    ('company_members','id'),
    ('company_members','invited_by'),
    ('company_members','invited_email'),
    ('company_members','role'),
    ('company_members','status'),
    ('company_members','user_id'),
    ('creative_scores','ad_name'),
    ('creative_scores','audience_segment'),
    ('creative_scores','campaign_id'),
    ('creative_scores','company_id'),
    ('creative_scores','created_at'),
    ('creative_scores','creative_kind'),
    ('creative_scores','creative_url'),
    ('creative_scores','dominant_interest'),
    ('creative_scores','format_id'),
    ('creative_scores','id'),
    ('creative_scores','interests'),
    ('creative_scores','is_heuristic'),
    ('creative_scores','objective'),
    ('creative_scores','platform_id'),
    ('creative_scores','reel_quality'),
    ('creative_scores','thumbnail_url'),
    ('creative_scores','user_id'),
    ('creative_scores','verdict_class'),
    ('creative_scores','vision_scores'),
    ('creative_scores','visual_model'),
    ('creative_scores','visual_provider'),
    ('platform_connections','account_ref'),
    ('platform_connections','company_id'),
    ('platform_connections','created_at'),
    ('platform_connections','credentials'),
    ('platform_connections','id'),
    ('platform_connections','label'),
    ('platform_connections','last_synced_at'),
    ('platform_connections','provider'),
    ('platform_connections','status'),
    ('platform_connections','status_note'),
    ('platform_connections','updated_at'),
    ('platform_connections','user_id')
),
problems as (
  -- missing tables
  select '1_MISSING_TABLE'::text as issue, et.t as table_name, ''::text as column_name
  from expected_tables et
  where not exists (select 1 from information_schema.tables it
                    where it.table_schema='public' and it.table_name=et.t)
  union all
  -- missing columns (only on tables that exist)
  select '2_MISSING_COLUMN', ec.t, ec.c
  from expected_cols ec
  where exists (select 1 from information_schema.tables it
               where it.table_schema='public' and it.table_name=ec.t)
    and not exists (select 1 from information_schema.columns ic
               where ic.table_schema='public' and ic.table_name=ec.t and ic.column_name=ec.c)
  union all
  -- missing storage bucket (migration 0006)
  select '3_MISSING_BUCKET', 'ad-creatives', ''
  where not exists (select 1 from storage.buckets where id='ad-creatives')
)
select issue, table_name, column_name from problems
union all
select 'OK — schema matches app; nothing missing', '', ''
where not exists (select 1 from problems)
order by 1, 2, 3;
